name: CI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: echo "Instalando dependências..."

      - name: Build
        run: echo "Buildando projeto..."

      - name: Test
        run: echo "Rodando testes..."

      - name: Gerar TAG automática
        run: |
          echo "Simulando criação de tag"
      
      - name: Notificar erro
        if: failure()
        run: echo "Erro no pipeline!"

      - name: Enviar email se falhar
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: bianca071995@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Erro no pipeline 🚨"
          body: "O pipeline falhou. Verifique o GitHub Actions."
          to: bianca071995@gmail.com
          from: bianca071995@gmail.com
      
      - name: Força erro
        run: exit 1